contact_links:
  - name: Join nf-core
    url: https://nf-co.re/join
    about: Please join the nf-core community here
  - name: "Slack #morfrnaseq channel"
    url: https://nfcore.slack.com/channels/morfrnaseq
    about: Discussion about the nf-core/morfrnaseq pipeline
